config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'activity-report', to: 'activity_report#index'
  post 'companies', to: 'companies#create'
  post 'activity-events', to: 'activity_events#create'

  root to: 'home#index'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/activity_event.rb
class ActivityEvent < ApplicationRecord
  belongs_to :company
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/controllers/activity_events_controller.rb
class ActivityEventsController < ApplicationController
  def create
    AddActivityEventJob.perform_later(event_params.to_h)
    head :ok
  end

  private

  def event_params
    params.require(:activity_event).permit(
      :company_id, :driver_id, :timestamp,
      :latitude, :longitude, :accuracy, :speed
    )
  end
end

app/controllers/activity_report_controller.rb
class ActivityReportController < ApplicationController
  def index
    return render status: :bad_request if driver_id.zero? || !date

    @report = DriverTracker.generate_report_interactor.run(driver_id, date)
    render status: :ok
  end

  private

  def driver_id
    report_params[:driver_id].to_i
  end

  def date
    Date.parse(report_params[:date])
  rescue TypeError, ArgumentError
    nil
  end

  def report_params
    params.permit(:driver_id, :date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def create
    response = DriverTracker.company_interactor.create(field: field_param)
    if response[:status] == :success
      render json: response, status: :created
    else
      render json: response, status: :unprocessable_entity
    end
  end

  private

  def field_param
    JSON.parse(company_params[:field])
  rescue JSON::ParserError
    nil
  end

  def company_params
    params.require(:company).permit(:field)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/activity_report_helper.rb
module ActivityReportHelper
  def presentable_time(seconds)
    total_minutes = seconds.to_i / 60
    hours = total_minutes / 60
    minutes = total_minutes % 60

    return "#{hours}h" if minutes.zero?

    "#{hours}:#{minutes.to_s.rjust(2, '0')}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activity_report/index.html.erb
<% if !@report %>
  Please provide a valid driver_id and date
<% else %>
  <p>Driver ID: <%= @report.driver_id %></p>
  <p>Date: <%= @report.date %></p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>From</th>
        <th>To</th>
        <th>Activity</th>
        <th>Time</th>
      </tr>
    </thead>
    <tbody>
      <% @report.rows.each do |row| %>
        <tr>
          <td><%= row.from.to_s(:time) %></td>
          <td><%= row.to.to_s(:time) %></td>
          <td><%= row.activity.capitalize %></td>
          <td><%= presentable_time(row.time) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/home/index.html.erb
<h1>Driver Tracker</h1>

<p>
  Driver Tracker is an application to track driver's activities on farms.
</p>

<h2>Activity Report</h2>

<p>
  Access the following link to see the report:
</p>

<p>
  <% url = activity_report_url(driver_id: 1, date: '2018-04-01') %>
  <%= link_to(url, url) %>
</p>

<p>
  Change the <strong>date</strong> and <strong>driver_id</strong> parameters to fetch other reports. Try the values <strong>1</strong> and <strong>2</strong> for <strong>driver_id</strong> and <strong>2018-04-01</strong> and <strong>2018-04-02</strong> for <strong>date</strong>.
</p>

<h2>Creating Companies</h2>

<p>
  You can create a new company through the API with the following <strong>curl</strong> command:
</p>

<pre>
  curl -X POST \
    <%= companies_url %> \
    -H 'Cache-Control: no-cache' \
    -H 'Content-Type: application/json' \
    -d '{
  	"company": {
  		"field": "[[10, 10], [10, 20], [20, 20], [20, 10], [10, 10]]"
  	}
  }'
</pre>

<p>
  The <strong>fields</strong> parameter is the field polygon and must be a string in the format of an array of arrays.
</p>

<h2>Adding Activity Events</h2>

<p>
  You can add a driver activity event through the API with the following <strong>curl</strong> command:
</p>

<pre>
  curl -X POST \
    <%= activity_events_url %> \
    -H 'Cache-Control: no-cache' \
    -H 'Content-Type: application/json' \
    -d '{
  	"activity_event": {
  		"company_id": 1,
          "driver_id": 1,
          "timestamp": "2018-04-01T12:33:15",
          "latitude": 3,
          "longitude": 4,
          "accuracy": 4,
          "speed": 10
  	}
  }'
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DriverTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>